language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pip install coveralls'
  - 'pipenv install'
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE puppy_store_drf;" -U postgres
  - psql -c "CREATE USER rufus WITH PASSWORD 'tykenyke';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE puppy_store_drf TO rufus;" -U postgres
script:
  - 'coverage run --source="." manage.py test'
  - 'coverage report'
after_success:
  - coveralls