language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pip install coveralls'
  - 'pipenv install'
services:
  - postgresql
before_script:
  - psql -c "create database puppy_store_drf; create user rufus with encrypted password 'tykenyke'; grant all privileges on database puppy_store_drf to rufus;" -U postgres
script:
  - 'coverage run --source="." manage.py test'
  - 'coverage report'
after_success:
  - coveralls